name: Build

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**" 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Build
        env:
          VITE_APP_URL: ${{ vars.VITE_APP_URL }}
          VITE_SPOTIFY_CLIENT_ID: ${{ secrets.VITE_SPOTIFY_CLIENT_ID }}
          VITE_REDIRECT_TARGET: ${{ vars.VITE_REDIRECT_TARGET }}
          VITE_SENTRY_DSN: ${{ vars.VITE_SENTRY_DSN }}
          SENTRY_ORG: ${{ vars.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ vars.SENTRY_PROJECT }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        run: npm run build
